spring:
  main:
    #解决循环依赖
    allow-circular-references: true
  application:
    name: packing-lot-system
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/packinglotdb
    username: root
    password: root
  #session ????????
  session:
    timeout: 86400
  jackson:
    time-zone: GMT+8

server:
  port: 8899

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

pagehelper:
  # 数据库方言 mysql
  helper-dialect: mysql
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，
  # 用于从对象中根据属性名取值
  #  默认值为 countSql
  params: countSql
  # 分页参数合理化
  # 默认是false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页；
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  # 默认值 false
  support-methods-arguments: true